---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgAUOO6nP67pliatflo1maIfRXzMlR3s5ZG7FIedtpj/wz3Kq/84l0HpktQuSrk7ile3CH8XBrK+rPvjrwYWc2cM334gL60Lxf1GkIZdb+52mDeVXieQHVmJ4JowYs83HD90dpNn454cJT+cJ5+o4RNGWwbMPfg+Xz4+z+wiR7cz74QeYdjFcVBpj5CsxI5iqwrBTvlXPSTYwGkmEY8ZsprkupcI64fZQLJQ//JP8uYh0W2uBHS/pUrnBxbv6zvYE5+vII4etSQKhscKfn7pBcw8GG0Cppu9f+clh2qg6c3iBVk7CzdYEk2sEvM3qJWxPF87a5oEWE5eDCL4/NZo/VrBNyCVjoVK1I3Oo61XTPK9KUlhsxWmA4IDvjOza2nuTmFWZuKB6s/X9QjYgZsVkcrOtd/tAUJcZ/D2+ZypIF1I8I42LjgbJXcG/RWbyaL7p+ZK1LgCo28wNvhCpwf1wBzi3GhYakisRUkP/8gfvIF4U1B2MAD+qMjS28fMhOJ+2Uf3T7atd3rucDjh0K76kMuuA4aBItAs8V/eCAsHhgTdb9/vYYoYodWGv/rkomonmMgWvsfMWrK/UDgdES51F6yceh46b+9NjwMcoLWruObUWog2L4Elkeb1QR2j88Rv5N8zIBoMjtEKmAAVoXd54sefaO4YrgMSdyoDu827jEq2KEbaMyU47V22BQ7BdjLIyAloOZ+8o00nFxQ4DMDNJIKCPK6qg31+lXcaYavJN2id0owfCPuT0Bbp
  template:
    metadata:
      name: github
      namespace: fluxcdtutorial
