---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgB0ATEZ4MF7jUYdfmGEl5acxdCZXMrDZpu2PNNiHgy+XvEBLBNKt9zDCVIAl4hK5bSJMiGC1FBrl5VTMEb1leqOgHx4cE40b77A/g7+faOrxvoKpwQbU/YTn+xJlXC/9O+SEWZ8MT1XLfnmspFmaVJj3rsRac/fxcDNyuuSdYvAPiJ1Am/mNg24QIFbSCVW9iXneTnxMx8Vp+wIUM4Y54Ob1Xb+NycJUT54ckLwnNeiKsm3DWzKR+dSaIYM2wgFfIRLQitc81F/vs2w6qD9BqJq25YAoCFPnizdVNMqEHRKnyMP60hB059IbCebtayzhCzUabGia5cSnHBUVupl8R950PrtjOVLuuP+t+qu63x+ynf40TZqEZp82+Z35BLUjf2lvrVRUkR1M0mqoWbl+CbULJQW9cpXNt83i+UJffEdRXf1U4C52jGMrpoC9i65KLh+KcsQABRiOiKkjLZ8uPVP09+VgCeKbu/MzqMO5m9N7tXdbhRl1RiBaaPJ9075vPYpGxXmI3r7kjQx1pCH7MHhXelb8OxHGRQQdwyWdast7hn6s2qVJGsMBr34Bun7TcA5tPsj79vqBx6a6m2EtadEYQtY3yv7367LfNlSksj8dXFmLopEGV+g6AG195D2pNoqH19z4c2qx3XtPQdwaBQDdMWMFrPavwgGZ8pi1l78q3mah4u0/oAF7mi41Or8piamyvRGDeUEUABL7YlEwTV7A5h/p6/G4FDCUdoEq4yBmifK0l/ABhDp
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: fluxcdtutorial
