apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd-tutorial-app
  namespace: fluxcdtutorial
spec:
  interval: 30s
  path: ./deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-tutorial-app
